### PR TITLE
More parameters

### PR DESCRIPTION
**Pull request by FelixDubois**
Hi !
I have added some commands :
- the output file name
- show or hide the amount of comments
- fill or not the like button
- fill or not the comment button

### CODE REVIEW

**Comment by Jolly-Pirate** [comment]
Increasing the scale to 2 is a good idea, it yields better and cleaner resolutions. However, keep in mind that when using the --width parameter, the final width is doubled because of the scaling.

Is it possible to remove the "Follow" string next to the user's account?
image

**Comment by FelixDubois** [comment]
Here you go @Jolly-Pirate. I hadn't noticed the thing about the scale so thanks 👍

**Comment by Jolly-Pirate** [comment]
Awesome, removing the Follow button works.

**Comment by Jolly-Pirate** [comment]
About the scaling, it could be passed on as a cli parameter instead of hard coding it.

**Comment by Jolly-Pirate** [comment]
Thanks for adding the scale option, but it conflicts with the current one `-s, --show-comments                   Show comments`
Gives an error `Error: Duplicate flags named "s"`

May I suggest changing it to `x` (as in multiplier) and don't forget to update the readme :)

**Comment by Jolly-Pirate** [comment]
@FelixDubois I found a little bug, when the `--show-thread` and `--hide-follow-button` options are enabled, the Follow button appears in the parent tweet.

snap-tweet-AlfrescoDent-1604069387664760832-thread

**Comment by privatenumber** [comment]
Thanks for the PR @FelixDubois 

Ideally each feature:
1. Has a feature request associated with it so the use-cases, motivations, and alternatives are clear
2. Are introduced in it's own PR so they're they're easily reviewable and mergable


Right now I'm not clear on what changes you're introducing and why.

**Comment by FelixDubois** [comment]
So I have to make a PR for each parameter I need to add?

**Comment by privatenumber** [comment]
In open source projects, you should start by creating an Issue describing the feature request. The feature request should include the motivations for the request, use-cases, and alternatives. The Issue thread can host a discussion about the feature before it's approved. Once approved, anyone can open a PR to address the request.

By making a PR for each feature request, they can be easily reviewed and merged without being blocked by unrelated concerns in the PR.

**Pull request closed without merging**
